"""gold corpus annotation tables (validator calibration)

Revision ID: 4d74aae79689
Revises: c8d9e0f1a2b3
Create Date: 2026-08-24 00:00:00.000000

Backs the 50-song blind double-annotation corpus used to calibrate the
transcription-quality validator before it can run unsupervised. Three new
tables, fully separate from `jobs` (these are never client jobs):

- corpus_songs: metadata + R2 pointer for a gold-corpus song. The audio
  itself is not duplicated — it already lives in R2 the same way job audio
  does; this row just points at the existing key.
- corpus_annotator_tokens: one row per (non-technical) human annotator.
  Auth model is a long random token embedded in a URL
  (`/annotate/{token}`), generated by an admin — no username/password, no
  expiry (the annotator must never get logged out mid-song).
- corpus_annotations: one annotator's segment markup for one song, unique
  per (song, annotator) so the same annotator can't accidentally create two
  competing drafts. Blindness (annotator A never sees annotator B's row) is
  enforced in the API layer, not the schema — see corpus.py.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "4d74aae79689"
down_revision: Union[str, Sequence[str], None] = "c8d9e0f1a2b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "corpus_songs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("artist", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("audio_r2_key", sa.Text(), nullable=False),
        sa.Column("audio_sha256", sa.String(length=64), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )

    op.create_table(
        "corpus_annotator_tokens",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_corpus_annotator_tokens_token", "corpus_annotator_tokens", ["token"],
        unique=True,
    )

    op.create_table(
        "corpus_annotations",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "song_id", sa.Integer(),
            sa.ForeignKey("corpus_songs.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "annotator_token_id", sa.Integer(),
            sa.ForeignKey("corpus_annotator_tokens.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "segments", postgresql.JSONB().with_variant(sa.JSON(), "sqlite"),
            nullable=False, server_default="[]",
        ),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="draft"),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.UniqueConstraint(
            "song_id", "annotator_token_id",
            name="uq_corpus_annotation_song_annotator",
        ),
    )
    op.create_index(
        "ix_corpus_annotations_song_id", "corpus_annotations", ["song_id"],
    )
    op.create_index(
        "ix_corpus_annotations_annotator_token_id", "corpus_annotations",
        ["annotator_token_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_corpus_annotations_annotator_token_id", table_name="corpus_annotations")
    op.drop_index("ix_corpus_annotations_song_id", table_name="corpus_annotations")
    op.drop_table("corpus_annotations")
    op.drop_index("ix_corpus_annotator_tokens_token", table_name="corpus_annotator_tokens")
    op.drop_table("corpus_annotator_tokens")
    op.drop_table("corpus_songs")
