// Three-way merge for lyric segments. The editor keeps `_id` local-only and
// persists `segment_id` so a correction in another row can be merged without
// treating the whole document as one conflicting blob.

export function decorateSegments(segments = []) {
  return segments.map((segment, index) => {
    const stable = segment?.segment_id ?? segment?.id ?? segment?._id ?? String(index);
    const localId = Number.isFinite(segment?._id) ? segment._id : index;
    return { ...segment, _id: localId, segment_id: String(stable) };
  });
}

export function persistedSegments(segments = []) {
  return segments.map(({ _id, ...segment }) => segment);
}

// The backend stores timings rounded to 4 decimals (`editor.py`: `round(start, 4)`),
// but the client kept the raw float it sent. Comparing one against the other made
// EVERY timeline drag look like a remote edit -> false conflict -> the editor
// locked into a terminal `conflict` state with no way out. Quantise both sides to
// the precision the server actually persists before comparing.
const TIME_DECIMALS = 4;

function quantizeTime(value) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return value;
  const factor = 10 ** TIME_DECIMALS;
  return Math.round(parsed * factor) / factor;
}

function comparable(segment) {
  if (segment == null) return null;
  // These fields are local identity or renderer-produced metadata. They can
  // legitimately change when a background/typography render finishes and do
  // not represent a lyric edit by the operator.
  const { _id, id, segment_id, words, review, ...rest } = segment;
  // Assigning existing keys preserves their position, so the JSON.stringify
  // comparison in `equal()` stays order-stable.
  if ("start" in rest) rest.start = quantizeTime(rest.start);
  if ("end" in rest) rest.end = quantizeTime(rest.end);
  return rest;
}

function sortForComparison(segments = []) {
  return [...segments].sort((a, b) => {
    const start = Number(a?.start || 0) - Number(b?.start || 0);
    if (Math.abs(start) > 1e-4) return start;
    const end = Number(a?.end || 0) - Number(b?.end || 0);
    if (Math.abs(end) > 1e-4) return end;
    return String(a?.text || "").localeCompare(String(b?.text || ""));
  });
}

/**
 * Compare the operator-owned lyric content, ignoring local ids and metadata
 * generated by the renderer. This is intentionally stricter than a text-only
 * comparison: timing and layout edits still count as real edits.
 */
export function segmentsEquivalent(left = [], right = []) {
  if (!Array.isArray(left) || !Array.isArray(right) || left.length !== right.length) return false;
  const a = sortForComparison(left);
  const b = sortForComparison(right);
  return a.every((segment, index) => {
    const other = b[index];
    if (Math.abs(Number(segment?.start || 0) - Number(other?.start || 0)) > 1e-3) return false;
    if (Math.abs(Number(segment?.end || 0) - Number(other?.end || 0)) > 1e-3) return false;
    return equal(segment, other);
  });
}

function equal(a, b) {
  return JSON.stringify(comparable(a)) === JSON.stringify(comparable(b));
}

function keyOf(segment, index) {
  return String(segment?.segment_id ?? segment?.id ?? segment?._id ?? `index:${index}`);
}

function indexed(segments) {
  const map = new Map();
  segments.forEach((segment, index) => map.set(keyOf(segment, index), segment));
  return map;
}

/**
 * Merge base → local and base → remote. A field/document is only considered
 * conflicting when both sides changed the same stable segment differently.
 */
export function mergeThreeWay(base = [], local = [], remote = []) {
  const baseMap = indexed(base);
  const localMap = indexed(local);
  const remoteMap = indexed(remote);
  const order = [];
  local.forEach((segment, index) => order.push(keyOf(segment, index)));
  remote.forEach((segment, index) => {
    const key = keyOf(segment, index);
    if (!order.includes(key)) order.push(key);
  });

  const conflicts = [];
  const merged = [];
  for (const key of order) {
    const b = baseMap.get(key);
    const l = localMap.get(key);
    const r = remoteMap.get(key);
    if (equal(l, r)) {
      if (l != null) merged.push(l);
      continue;
    }
    if (equal(b, l)) {
      if (r != null) merged.push(r);
      continue;
    }
    if (equal(b, r)) {
      if (l != null) merged.push(l);
      continue;
    }
    conflicts.push({ key, base: b || null, local: l || null, remote: r || null });
    if (l != null) merged.push(l);
  }
  return { merged: decorateSegments(merged), conflicts };
}
