// Three-way merge for lyric segments. The editor keeps `_id` local-only and
// persists `segment_id` so a correction in another row can be merged without
// treating the whole document as one conflicting blob.

export function decorateSegments(segments = []) {
  return segments.map((segment, index) => {
    const stable = segment?.segment_id ?? segment?.id ?? segment?._id ?? String(index);
    const localId = Number.isFinite(segment?._id) ? segment._id : index;
    return { ...segment, _id: localId, segment_id: String(stable) };
  });
}

export function persistedSegments(segments = []) {
  return segments.map(({ _id, ...segment }) => segment);
}

// The backend stores timings rounded to 4 decimals (`editor.py`: `round(start, 4)`),
// but the client kept the raw float it sent. Comparing one against the other made
// EVERY timeline drag look like a remote edit -> false conflict -> the editor
// locked into a terminal `conflict` state with no way out. Quantise both sides to
// the precision the server actually persists before comparing.
const TIME_DECIMALS = 4;

function quantizeTime(value) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return value;
  const factor = 10 ** TIME_DECIMALS;
  return Math.round(parsed * factor) / factor;
}

function comparable(segment) {
  if (segment == null) return null;
  // These fields are local identity or renderer-produced metadata. They can
  // legitimately change when a background/typography render finishes and do
  // not represent a lyric edit by the operator.
  const { _id, id, segment_id, words, review, ...rest } = segment;
  // Assigning existing keys preserves their position, so the JSON.stringify
  // comparison in `equal()` stays order-stable.
  if ("start" in rest) rest.start = quantizeTime(rest.start);
  if ("end" in rest) rest.end = quantizeTime(rest.end);
  return rest;
}

function sortForComparison(segments = []) {
  return [...segments].sort((a, b) => {
    const start = Number(a?.start || 0) - Number(b?.start || 0);
    if (Math.abs(start) > 1e-4) return start;
    const end = Number(a?.end || 0) - Number(b?.end || 0);
    if (Math.abs(end) > 1e-4) return end;
    return String(a?.text || "").localeCompare(String(b?.text || ""));
  });
}

/**
 * Compare the operator-owned lyric content, ignoring local ids and metadata
 * generated by the renderer. This is intentionally stricter than a text-only
 * comparison: timing and layout edits still count as real edits.
 */
export function segmentsEquivalent(left = [], right = []) {
  if (!Array.isArray(left) || !Array.isArray(right) || left.length !== right.length) return false;
  const a = sortForComparison(left);
  const b = sortForComparison(right);
  return a.every((segment, index) => {
    const other = b[index];
    if (Math.abs(Number(segment?.start || 0) - Number(other?.start || 0)) > 1e-3) return false;
    if (Math.abs(Number(segment?.end || 0) - Number(other?.end || 0)) > 1e-3) return false;
    return equal(segment, other);
  });
}

function equal(a, b) {
  return JSON.stringify(comparable(a)) === JSON.stringify(comparable(b));
}

function keyOf(segment, index) {
  return String(segment?.segment_id ?? segment?.id ?? segment?._id ?? `index:${index}`);
}

// Rows sharing one `segment_id` are NOT hypothetical: hasta este fix,
// duplicar/dividir una línea clonaba el `segment_id` del padre, y los jobs
// editados antes siguen cargando esos duplicados. Con la clave pelada, cada
// grupo de duplicados colapsaba en el `Map` (last-write-wins) y el merge
// devolvía UNA fila por clave distinta: 44 líneas entraban y salían 38, sin
// conflicto y sin aviso (job f866cbcf0e49, UMG Chile, 1-sep-2026 — el
// operador había duplicado el estribillo a mano y perdió las 5 repeticiones
// al reabrir el editor). Calificar la clave con el ordinal de aparición
// mantiene distintas a las filas duplicadas y aparea la n-ésima copia de un
// lado con la n-ésima del otro.
function occurrenceKeys(segments) {
  const seen = new Map();
  return segments.map((segment, index) => {
    const stable = keyOf(segment, index);
    const occurrence = seen.get(stable) || 0;
    seen.set(stable, occurrence + 1);
    return occurrence === 0 ? stable : `${stable}#${occurrence}`;
  });
}

// El ordinal es un detalle interno del merge: lo que sale en `conflicts[].key`
// (contrato con el editor) sigue siendo el id estable pelado.
function stableIdOf(key) {
  const hash = key.lastIndexOf("#");
  return hash === -1 ? key : key.slice(0, hash);
}

function indexed(segments, keys) {
  const map = new Map();
  segments.forEach((segment, index) => map.set(keys[index], segment));
  return map;
}

/**
 * Merge base → local and base → remote. A field/document is only considered
 * conflicting when both sides changed the same stable segment differently.
 */
export function mergeThreeWay(base = [], local = [], remote = []) {
  const baseKeys = occurrenceKeys(base);
  const localKeys = occurrenceKeys(local);
  const remoteKeys = occurrenceKeys(remote);
  const baseMap = indexed(base, baseKeys);
  const localMap = indexed(local, localKeys);
  const remoteMap = indexed(remote, remoteKeys);
  const order = [];
  const ordered = new Set();
  for (const key of localKeys) {
    if (ordered.has(key)) continue;
    ordered.add(key);
    order.push(key);
  }
  for (const key of remoteKeys) {
    if (ordered.has(key)) continue;
    ordered.add(key);
    order.push(key);
  }

  const conflicts = [];
  const merged = [];
  for (const key of order) {
    const b = baseMap.get(key);
    const l = localMap.get(key);
    const r = remoteMap.get(key);
    if (equal(l, r)) {
      if (l != null) merged.push(l);
      continue;
    }
    if (equal(b, l)) {
      if (r != null) merged.push(r);
      continue;
    }
    if (equal(b, r)) {
      if (l != null) merged.push(l);
      continue;
    }
    conflicts.push({
      key: stableIdOf(key), base: b || null, local: l || null, remote: r || null,
    });
    if (l != null) merged.push(l);
  }

  // Invariante: cada fila de salida tiene que venir de una fila de entrada
  // DISTINTA. Ese es exactamente el contrato que rompía el bug: con la clave
  // pelada, `order` visitaba la clave duplicada N veces y `localMap.get(key)`
  // devolvía siempre la MISMA fila (la última del grupo), así que el merge
  // salía con 44 filas pero sólo 38 contenidos distintos — y el deduplicador
  // de colisiones de `canonicalizeEditorSegments` remataba borrando las 6
  // copias sobrantes. Nada "se perdía" acá adentro: se clonaba, y el borrado
  // ocurría dos pasos después. Un guardrail de cantidad no lo habría visto;
  // éste sí. `[merge-dup]` lo reenvía observability.js a Sentry (mismo
  // mecanismo que `[reseed-storm]`).
  const seenSources = new Set();
  const deduped = [];
  const repeated = [];
  for (const segment of merged) {
    if (seenSources.has(segment)) {
      repeated.push(segment);
      continue;
    }
    seenSources.add(segment);
    deduped.push(segment);
  }
  if (repeated.length > 0) {
    // eslint-disable-next-line no-console
    console.warn("[merge-dup] three-way merge emitted the same row more than once", {
      repeated: repeated.length,
      texts: repeated.slice(0, 5).map((segment) => String(segment?.text || "")),
      local: local.length,
      remote: remote.length,
      merged: merged.length,
    });
  }
  return { merged: decorateSegments(deduped), conflicts };
}
