#!/usr/bin/env python3
"""Generate the JS<->Python render-parity fixture.

The frontend previews mirror the render's sizing/fade math (lyricTiers.js
<-> ass_render.py). That mirror used to be guarded only by hand-copied
constants and a stale test, which is how the "preview shows the text
bigger than the video" bug shipped. This script derives a fixture from
the PYTHON side (the render is the source of truth) and both test suites
assert against it:

  - backend/tests/test_render_parity_fixture.py regenerates the fixture
    in memory and fails if the committed JSON is stale (i.e. someone
    changed ass_render without re-running this script).
  - frontend/src/lib/renderParity.test.js evaluates the real JS functions
    (lyricTiers.lyricFontPx / FADE_SECONDS / fadeSeconds) over the same
    matrix and fails on any numeric divergence.

Regenerate after touching lyric_fontsize/_FONT_SIZE_NORM/_FADE_DURATIONS_S:

    cd lyricgen/backend && python3 scripts/gen_render_parity_fixture.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ass_render import (  # noqa: E402
    _FADE_DURATIONS_S,
    _FONT_SIZE_NORM,
    fade_seconds,
    font_size_factor,
    lyric_fontsize,
)
from pipeline import (  # noqa: E402
    _CONCEPT_SCENE_GUIDE,
    _FONT_CATALOGUE,
    _MOVEMENT_STYLE_RULES,
    _normalize_movement_style,
)
from fx_compositor import EFFECTS as EFFECT_CODES  # noqa: E402
from tenant_style import strip_trailing_punctuation  # noqa: E402

FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "frontend", "src", "shared", "renderParity.json"
)

# Text lengths covering both tier boundaries (50/51, 80/81) plus interior
# and extreme values; font_scales covering both clamp edges (0.4/1.7 are
# out-of-range on purpose) and the 0.75 case whose product lands on an
# exact .5 (banker's-rounding trap: Python round(52.5)=52, JS Math.round=53).
# Entradas con las que se sondea _normalize_movement_style: los 5 códigos
# canónicos, TODOS los alias que la función acepta, los valores que el editor
# de escena y el derivado por energía emiten ("dinamico"), variantes de
# capitalización/acento, y basura. El espejo JS (catalogCodes.normalizeMovementCode)
# tiene que coincidir en las tres columnas.
_MOVEMENT_NORMALIZATION_PROBES = [
    "", "  ",
    "estatico", "sutil", "estandar", "foto-parallax", "animado",
    "static", "estatica", "estática", "estático", "fija", "fixed", "tripod",
    "locked", "still", "camara-fija", "camara fija",
    "subtle", "minimal", "minimo",
    "standard", "default",
    "dinamico", "dinámico", "dynamic",
    "photo", "parallax", "foto+parallax", "foto_parallax", "foto fija",
    "animated", "illustration", "cartoon",
    "ESTATICO", "Dinamico", "  Estatica  ",
    "basura", "photo-parallax",
]

# Sondas de strip_trailing_punctuation. Incluyen los casos reales que UMG
# pidió ("sacar los puntos al final de cada frase") y los que NO hay que
# tocar: los signos de interrogación/exclamación cargan sentido y nadie
# pidió sacarlos, y la puntuación a mitad de línea ("No, no puedo") es
# legible. La línea que es sólo puntos vuelve intacta a propósito: un
# cartel estilístico "..." no debe desaparecer solo.
_PUNCTUATION_PROBES = [
    "",
    "Costumbres argentinas",
    "Costumbres argentinas.",
    "Y sigue el tren...",
    "Y sigue el tren…",
    "No hay nadie mas que vos y yo,",
    "Dime una cosa;",
    "Escuchame bien:",
    "¿Quien te mira?",
    "¡La argentinidad al palo!",
    "No, no puedo mas.",
    "Mil horas.   ",
    "...",
    "…",
    ".",
    "   ",
]

TEXT_LENGTHS = [1, 30, 50, 51, 80, 81, 120, 200]
FONT_SCALES = [0.4, 0.6, 0.75, 0.9, 1.0, 1.15, 1.3, 1.5, 1.7]
FAMILIES = sorted(_FONT_SIZE_NORM.keys()) + ["unknown"]

# fade_seconds sample points: normal duration, the dur/3 cap, zero and
# negative durations, and an unknown transition.
FADE_CASES = [
    ("cut", 10.0),
    ("fade", 10.0),
    ("fade_slow", 10.0),
    ("fade", 0.3),
    ("fade_slow", 0.6),
    ("fade", 0.0),
    ("fade", -1.0),
    ("bogus", 10.0),
]


def build_fixture() -> dict:
    font_sizes = []
    for text_len in TEXT_LENGTHS:
        for fs in FONT_SCALES:
            for fam in FAMILIES:
                factor = font_size_factor("" if fam == "unknown" else fam)
                font_sizes.append({
                    "text_len": text_len,
                    "font_scale": fs,
                    "family": fam,
                    "px": lyric_fontsize(text_len, 1.0, fs, factor),
                })
    fades = [
        {
            "transition": tr,
            "seg_duration": dur,
            "seconds": round(fade_seconds(tr, dur), 9),
        }
        for tr, dur in FADE_CASES
    ]
    return {
        "_comment": (
            "GENERATED by backend/scripts/gen_render_parity_fixture.py — do not "
            "hand-edit. Source of truth: ass_render.py. Asserted by "
            "backend/tests/test_render_parity_fixture.py (freshness) and "
            "frontend/src/lib/renderParity.test.js (JS mirror)."
        ),
        "font_scale_clamp": {"min": 0.6, "max": 1.5},
        "tiers": [
            {"max_chars": 50, "base_px": 85},
            {"max_chars": 80, "base_px": 70},
            {"max_chars": None, "base_px": 55},
        ],
        "font_size_norm": dict(sorted(_FONT_SIZE_NORM.items())),
        "fade_durations_s": dict(sorted(_FADE_DURATIONS_S.items())),
        "font_sizes": font_sizes,
        "fades": fades,
        # Hand-mirrored option catalogs (worker renders what the dropdown
        # promised). The frontend's picker CODES must equal these — the "" /
        # Auto option is frontend-only and excluded from the contract.
        "catalogs": {
            "fonts": sorted(f["id"] for f in _FONT_CATALOGUE),
            "concepts": sorted(_CONCEPT_SCENE_GUIDE.keys()),
            "movements": sorted(_MOVEMENT_STYLE_RULES.keys()),
            "effects": sorted(EFFECT_CODES),
        },
        # Tabla de verdad de _normalize_movement_style. `movement_style` viaja
        # como TEXTO LIBRE y se persiste CRUDO en render_params, así que el
        # wizard tiene que normalizarlo para saber qué tarjeta resaltar — y si
        # el espejo JS divergiera, el wizard marcaría una opción que el render
        # no va a respetar (o ninguna). Se genera en vez de mantenerse a mano
        # porque un mapa hand-copiado es exactamente lo que este fixture existe
        # para prevenir.
        "movement_normalization": {
            raw: _normalize_movement_style(raw)
            for raw in sorted(_MOVEMENT_NORMALIZATION_PROBES)
        },
        # Tabla de verdad de tenant_style.strip_trailing_punctuation. La
        # preview del wizard pinta la letra con su propio applyCase; si el
        # espejo JS no sacara los mismos puntos, el operador vería en la
        # preview algo distinto de lo que sale renderizado — que es
        # exactamente el bug de fidelidad que este fixture existe para
        # prevenir. Los casos cubren: punto final, elipsis, coma/;/:,
        # signos que NO se tocan (? !), puntuación a mitad de línea,
        # espacios finales y la línea que es sólo puntuación.
        "strip_trailing_punctuation": {
            raw: strip_trailing_punctuation(raw)
            for raw in sorted(_PUNCTUATION_PROBES)
        },
    }


def main() -> None:
    fixture = build_fixture()
    out = os.path.abspath(FIXTURE_PATH)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        json.dump(fixture, f, indent=1, sort_keys=True)
        f.write("\n")
    print(f"wrote {out} ({len(fixture['font_sizes'])} font-size cases)")


if __name__ == "__main__":
    main()
